/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_ServedGUMMEIsItem_H_
#define	_S1AP_ServedGUMMEIsItem_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-ServedPLMNs.h"
#include "S1AP-ServedGroupIDs.h"
#include "S1AP-ServedMMECs.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* S1AP-ServedGUMMEIsItem */
typedef struct S1AP_ServedGUMMEIsItem {
	S1AP_ServedPLMNs_t	 servedPLMNs;
	S1AP_ServedGroupIDs_t	 servedGroupIDs;
	S1AP_ServedMMECs_t	 servedMMECs;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ServedGUMMEIsItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ServedGUMMEIsItem;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_ServedGUMMEIsItem_H_ */
#include "asn_internal.h"
