/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_TargetID_H_
#define	_S1AP_TargetID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-TargeteNB-ID.h"
#include "S1AP-TargetRNC-ID.h"
#include "S1AP-CGI.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_TargetID_PR {
	S1AP_TargetID_PR_NOTHING,	/* No components present */
	S1AP_TargetID_PR_targeteNB_ID,
	S1AP_TargetID_PR_targetRNC_ID,
	S1AP_TargetID_PR_cGI,
	/* Extensions may appear below */
	
} S1AP_TargetID_PR;

/* S1AP-TargetID */
typedef struct S1AP_TargetID {
	S1AP_TargetID_PR present;
	union S1AP_TargetID_u {
		S1AP_TargeteNB_ID_t	 targeteNB_ID;
		S1AP_TargetRNC_ID_t	 targetRNC_ID;
		S1AP_CGI_t	 cGI;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_TargetID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_TargetID;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_TargetID_H_ */
#include "asn_internal.h"
