/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_AreaScopeOfMDT_H_
#define	_S1AP_AreaScopeOfMDT_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-CellBasedMDT.h"
#include "S1AP-TABasedMDT.h"
#include "NULL.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_AreaScopeOfMDT_PR {
	S1AP_AreaScopeOfMDT_PR_NOTHING,	/* No components present */
	S1AP_AreaScopeOfMDT_PR_cellBased,
	S1AP_AreaScopeOfMDT_PR_tABased,
	S1AP_AreaScopeOfMDT_PR_pLMNWide,
	/* Extensions may appear below */
	
} S1AP_AreaScopeOfMDT_PR;

/* S1AP-AreaScopeOfMDT */
typedef struct S1AP_AreaScopeOfMDT {
	S1AP_AreaScopeOfMDT_PR present;
	union S1AP_AreaScopeOfMDT_u {
		S1AP_CellBasedMDT_t	 cellBased;
		S1AP_TABasedMDT_t	 tABased;
		NULL_t	 pLMNWide;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_AreaScopeOfMDT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_AreaScopeOfMDT;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_AreaScopeOfMDT_H_ */
#include "asn_internal.h"
