/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_OverloadResponse_H_
#define	_S1AP_OverloadResponse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-OverloadAction.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_OverloadResponse_PR {
	S1AP_OverloadResponse_PR_NOTHING,	/* No components present */
	S1AP_OverloadResponse_PR_overloadAction,
	/* Extensions may appear below */
	
} S1AP_OverloadResponse_PR;

/* S1AP-OverloadResponse */
typedef struct S1AP_OverloadResponse {
	S1AP_OverloadResponse_PR present;
	union S1AP_OverloadResponse_u {
		S1AP_OverloadAction_t	 overloadAction;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_OverloadResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_OverloadResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_OverloadResponse_H_ */
#include "asn_internal.h"
