/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_ImmediateMDT_H_
#define	_S1AP_ImmediateMDT_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-MeasurementsToActivate.h"
#include "S1AP-ReportingTriggerMDT.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1AP_ThresholdEventA2;
struct S1AP_PeriodicReportingMDT;
struct ProtocolExtensionContainer;

/* S1AP-ImmediateMDT */
typedef struct S1AP_ImmediateMDT {
	S1AP_MeasurementsToActivate_t	 measurementsToActivate;
	S1AP_ReportingTriggerMDT_t	 reportingTriggerMDT;
	struct S1AP_ThresholdEventA2	*thresholdeventA2	/* OPTIONAL */;
	struct S1AP_PeriodicReportingMDT	*periodicReportingMDT	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_ImmediateMDT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_ImmediateMDT;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "S1AP-ThresholdEventA2.h"
#include "S1AP-PeriodicReportingMDT.h"
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_ImmediateMDT_H_ */
#include "asn_internal.h"
