/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_LastVisitedCell_Item_H_
#define	_S1AP_LastVisitedCell_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-LastVisitedEUTRANCellInformation.h"
#include "S1AP-LastVisitedUTRANCellInformation.h"
#include "S1AP-LastVisitedGERANCellInformation.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_LastVisitedCell_Item_PR {
	S1AP_LastVisitedCell_Item_PR_NOTHING,	/* No components present */
	S1AP_LastVisitedCell_Item_PR_e_UTRAN_Cell,
	S1AP_LastVisitedCell_Item_PR_uTRAN_Cell,
	S1AP_LastVisitedCell_Item_PR_gERAN_Cell,
	/* Extensions may appear below */
	
} S1AP_LastVisitedCell_Item_PR;

/* S1AP-LastVisitedCell-Item */
typedef struct S1AP_LastVisitedCell_Item {
	S1AP_LastVisitedCell_Item_PR present;
	union S1AP_LastVisitedCell_Item_u {
		S1AP_LastVisitedEUTRANCellInformation_t	 e_UTRAN_Cell;
		S1AP_LastVisitedUTRANCellInformation_t	 uTRAN_Cell;
		S1AP_LastVisitedGERANCellInformation_t	 gERAN_Cell;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_LastVisitedCell_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_LastVisitedCell_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_LastVisitedCell_Item_H_ */
#include "asn_internal.h"
