/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_CGI_H_
#define	_S1AP_CGI_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-PLMNidentity.h"
#include "S1AP-LAC.h"
#include "S1AP-CI.h"
#include "S1AP-RAC.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* S1AP-CGI */
typedef struct S1AP_CGI {
	S1AP_PLMNidentity_t	 pLMNidentity;
	S1AP_LAC_t	 lAC;
	S1AP_CI_t	 cI;
	S1AP_RAC_t	*rAC	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_CGI;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_CGI_H_ */
#include "asn_internal.h"
