/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_SONConfigurationTransfer_H_
#define	_S1AP_SONConfigurationTransfer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-TargeteNB-ID.h"
#include "S1AP-SourceeNB-ID.h"
#include "S1AP-SONInformation.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* S1AP-SONConfigurationTransfer */
typedef struct S1AP_SONConfigurationTransfer {
	S1AP_TargeteNB_ID_t	 targeteNB_ID;
	S1AP_SourceeNB_ID_t	 sourceeNB_ID;
	S1AP_SONInformation_t	 sONInformation;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_SONConfigurationTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_SONConfigurationTransfer;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_SONConfigurationTransfer_H_ */
#include "asn_internal.h"
