/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_LastVisitedEUTRANCellInformation_H_
#define	_S1AP_LastVisitedEUTRANCellInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-EUTRAN-CGI.h"
#include "S1AP-CellType.h"
#include "S1AP-Time-UE-StayedInCell.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* S1AP-LastVisitedEUTRANCellInformation */
typedef struct S1AP_LastVisitedEUTRANCellInformation {
	S1AP_EUTRAN_CGI_t	 global_Cell_ID;
	S1AP_CellType_t	 cellType;
	S1AP_Time_UE_StayedInCell_t	 time_UE_StayedInCell;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_LastVisitedEUTRANCellInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_LastVisitedEUTRANCellInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_LastVisitedEUTRANCellInformation_H_ */
#include "asn_internal.h"
