/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_RIMRoutingAddress_H_
#define	_S1AP_RIMRoutingAddress_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-GERAN-Cell-ID.h"
#include "S1AP-TargetRNC-ID.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_RIMRoutingAddress_PR {
	S1AP_RIMRoutingAddress_PR_NOTHING,	/* No components present */
	S1AP_RIMRoutingAddress_PR_gERAN_Cell_ID,
	/* Extensions may appear below */
	S1AP_RIMRoutingAddress_PR_targetRNC_ID
} S1AP_RIMRoutingAddress_PR;

/* S1AP-RIMRoutingAddress */
typedef struct S1AP_RIMRoutingAddress {
	S1AP_RIMRoutingAddress_PR present;
	union S1AP_RIMRoutingAddress_u {
		S1AP_GERAN_Cell_ID_t	 gERAN_Cell_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		S1AP_TargetRNC_ID_t	 targetRNC_ID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_RIMRoutingAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_RIMRoutingAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_RIMRoutingAddress_H_ */
#include "asn_internal.h"
