/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_S_TMSI_H_
#define	_S1AP_S_TMSI_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-MME-Code.h"
#include "S1AP-M-TMSI.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* S1AP-S-TMSI */
typedef struct S1AP_S_TMSI {
	S1AP_MME_Code_t	 mMEC;
	S1AP_M_TMSI_t	 m_TMSI;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_S_TMSI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_S_TMSI;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_S_TMSI_H_ */
#include "asn_internal.h"
