/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_EmergencyAreaID_Broadcast_H_
#define	_S1AP_EmergencyAreaID_Broadcast_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1AP_EmergencyAreaID_Broadcast_Item;

/* S1AP-EmergencyAreaID-Broadcast */
typedef struct S1AP_EmergencyAreaID_Broadcast {
	A_SEQUENCE_OF(struct S1AP_EmergencyAreaID_Broadcast_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_EmergencyAreaID_Broadcast_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_EmergencyAreaID_Broadcast;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "S1AP-EmergencyAreaID-Broadcast-Item.h"

#endif	/* _S1AP_EmergencyAreaID_Broadcast_H_ */
#include "asn_internal.h"
