/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_MDT_Configuration_H_
#define	_S1AP_MDT_Configuration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-MDT-Activation.h"
#include "S1AP-AreaScopeOfMDT.h"
#include "S1AP-MDTMode.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* S1AP-MDT-Configuration */
typedef struct S1AP_MDT_Configuration {
	S1AP_MDT_Activation_t	 mdt_Activation;
	S1AP_AreaScopeOfMDT_t	 areaScopeOfMDT;
	S1AP_MDTMode_t	 mDTMode;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_MDT_Configuration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_MDT_Configuration;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_MDT_Configuration_H_ */
#include "asn_internal.h"
