/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_E_RABLevelQoSParameters_H_
#define	_S1AP_E_RABLevelQoSParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-QCI.h"
#include "S1AP-AllocationAndRetentionPriority.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct S1AP_GBR_QosInformation;
struct ProtocolExtensionContainer;

/* S1AP-E-RABLevelQoSParameters */
typedef struct S1AP_E_RABLevelQoSParameters {
	S1AP_QCI_t	 qCI;
	S1AP_AllocationAndRetentionPriority_t	 allocationRetentionPriority;
	struct S1AP_GBR_QosInformation	*gbrQosInformation	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_E_RABLevelQoSParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_E_RABLevelQoSParameters;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "S1AP-GBR-QosInformation.h"
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_E_RABLevelQoSParameters_H_ */
#include "asn_internal.h"
