/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_BroadcastCompletedAreaList_H_
#define	_S1AP_BroadcastCompletedAreaList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-CellID-Broadcast.h"
#include "S1AP-TAI-Broadcast.h"
#include "S1AP-EmergencyAreaID-Broadcast.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_BroadcastCompletedAreaList_PR {
	S1AP_BroadcastCompletedAreaList_PR_NOTHING,	/* No components present */
	S1AP_BroadcastCompletedAreaList_PR_cellID_Broadcast,
	S1AP_BroadcastCompletedAreaList_PR_tAI_Broadcast,
	S1AP_BroadcastCompletedAreaList_PR_emergencyAreaID_Broadcast,
	/* Extensions may appear below */
	
} S1AP_BroadcastCompletedAreaList_PR;

/* S1AP-BroadcastCompletedAreaList */
typedef struct S1AP_BroadcastCompletedAreaList {
	S1AP_BroadcastCompletedAreaList_PR present;
	union S1AP_BroadcastCompletedAreaList_u {
		S1AP_CellID_Broadcast_t	 cellID_Broadcast;
		S1AP_TAI_Broadcast_t	 tAI_Broadcast;
		S1AP_EmergencyAreaID_Broadcast_t	 emergencyAreaID_Broadcast;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_BroadcastCompletedAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_BroadcastCompletedAreaList;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_BroadcastCompletedAreaList_H_ */
#include "asn_internal.h"
