/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_E_RABSetupItemBearerSURes_H_
#define	_S1AP_E_RABSetupItemBearerSURes_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-E-RAB-ID.h"
#include "S1AP-TransportLayerAddress.h"
#include "S1AP-GTP-TEID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* S1AP-E-RABSetupItemBearerSURes */
typedef struct S1AP_E_RABSetupItemBearerSURes {
	S1AP_E_RAB_ID_t	 e_RAB_ID;
	S1AP_TransportLayerAddress_t	 transportLayerAddress;
	S1AP_GTP_TEID_t	 gTP_TEID;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_E_RABSetupItemBearerSURes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_E_RABSetupItemBearerSURes;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProtocolExtensionContainer.h"

#endif	/* _S1AP_E_RABSetupItemBearerSURes_H_ */
#include "asn_internal.h"
