/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "../support/S1AP-PDU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted`
 */

#ifndef	_S1AP_MeasurementThresholdA2_H_
#define	_S1AP_MeasurementThresholdA2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "S1AP-Threshold-RSRP.h"
#include "S1AP-Threshold-RSRQ.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_MeasurementThresholdA2_PR {
	S1AP_MeasurementThresholdA2_PR_NOTHING,	/* No components present */
	S1AP_MeasurementThresholdA2_PR_threshold_RSRP,
	S1AP_MeasurementThresholdA2_PR_threshold_RSRQ,
	/* Extensions may appear below */
	
} S1AP_MeasurementThresholdA2_PR;

/* S1AP-MeasurementThresholdA2 */
typedef struct S1AP_MeasurementThresholdA2 {
	S1AP_MeasurementThresholdA2_PR present;
	union S1AP_MeasurementThresholdA2_u {
		S1AP_Threshold_RSRP_t	 threshold_RSRP;
		S1AP_Threshold_RSRQ_t	 threshold_RSRQ;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_MeasurementThresholdA2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_MeasurementThresholdA2;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_MeasurementThresholdA2_H_ */
#include "asn_internal.h"
